version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: chaoticipher
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mysqlapplicationtestdb
    ports:
      - "3306:3306"
    networks:
      - app-network

  jhipster:
    image: harshdwivedi295/mysqlapplicationtest:latest
    container_name: mysqlapplicationtest
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysqlapplicationtestdb
      SPRING_DATASOURCE_USERNAME: chaoticipher
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
